version: '3.3'

services:
  php_webserver:
    container_name: php_webserver
    image: php:8.1-apache
    ports:
      - 4001:80
    volumes:
      - ./src:/var/www/html/
#    depends_on:
#      - database
#    environment:
#      - DB_HOST=database
#      - DB_DATABASE=${DB_DATABASE}
#      - DB_USERNAME=${DB_USERNAME}
#      - DB_PASSWORD=${DB_PASSWORD}
#
#  database:
#    image: mysql:8
#    volumes:
#      - ./database_data/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_DATABASE}
#      MYSQL_USER: ${DB_USERNAME}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_ROOT_HOST: "%"
#
#  adminer:
#    image: adminer
#    ports:
#      - 8080:8080
#
#volumes:
#  database_data:

